TODO_AUTHOR_NAME="Jérémie DECOCK"
TODO_AUTHOR_EMAIL="jd.jdhp@gmail.com"
TODO_AUTHOR_WEB_SITE="www.jdhp.org"

TODO_COPYRIGHT_NOTICE="Copyright (c) 2016 ${TODO_AUTHOR_NAME} (${TODO_AUTHOR_WEB_SITE})"

TODO_PROJECT_INITIAL_DATE="YYYY-MM-DD"          # TODO
TODO_PROJECT_SHORT_DESC="TODO"                  # TODO one line

TODO_PROJECT_NAME="TODO"                        # TODO e.g. PyAX-12
TODO_PYTHON_PACKAGE_NAME="TODO"                 # TODO e.g. pyax12 (all in lower case and without special character)

TODO_PROJECT_GITHUB_ACCOUNT="jeremiedecock"     # TODO
TODO_PROJECT_GITHUB_REPOSITORY_NAME="TODO"      # TODO

TODO_PROJECT_GITHUB_URL="https://github.com/${TODO_PROJECT_GITHUB_ACCOUNT}/${TODO_PROJECT_GITHUB_REPOSITORY_NAME}"
TODO_PROJECT_ISSUE_TRACKER_URL="https://github.com/${TODO_PROJECT_GITHUB_ACCOUNT}/${TODO_PROJECT_GITHUB_REPOSITORY_NAME}/issues"

TODO_PROJECT_PYPI_URL="https://pypi.python.org/pypi/TODO_PYTHON_PACKAGE_NAME"

TODO_PROJECT_WEB_SITE_URL="http://www.jdhp.org/software_en.html#${TODO_PYTHON_PACKAGE_NAME}"

TODO_PROJECT_ONLINE_DOCUMENTATION_URL="http://${TODO_PYTHON_PACKAGE_NAME}.readthedocs.org"
TODO_PROJECT_ONLINE_API_DOCUMENTATION_URL="http://${TODO_PYTHON_PACKAGE_NAME}.readthedocs.org/en/latest/api.html"
